on:
  pull_request:
  push:
    branches:
      - master

name: CI

jobs:
  format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0'
          distribution: 'adopt'
      - run: |
          ./dev/javafmt
          if [[ $(git diff) != "" ]]
          then
              echo "code format error, please run the following commands:"
              echo "   mvn com.coveo:fmt-maven-plugin:format"
              exit 1
          fi

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0'
          distribution: 'adopt'
      - name: Install TiUP
        run: curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
      - name: Start TiUP Playground
        run: |
          /home/runner/.tiup/bin/tiup playground nightly --mode tikv-slim --kv 1 --without-monitor --kv.config /home/runner/work/client-java/client-java/.github/config/tikv_rawkv.toml --pd.config /home/runner/work/client-java/client-java/.github/config/pd.toml &> raw.out 2>&1 &
          sleep 1m 30s
          /home/runner/.tiup/bin/tiup playground nightly --mode tikv-slim --kv 1 --without-monitor --kv.config /home/runner/work/client-java/client-java/.github/config/tikv_txnkv.toml --pd.config /home/runner/work/client-java/client-java/.github/config/pd.toml &> txn.out 2>&1 &
          sleep 30s
          echo "RAWKV_PD_ADDRESSES=$(cat raw.out | grep -oP '(?<=PD client endpoints: \[)[0-9\.:]+(?=\])')" >> $GITHUB_ENV
          echo "TXNKV_PD_ADDRESSES=$(cat txn.out | grep -oP '(?<=PD client endpoints: \[)[0-9\.:]+(?=\])')" >> $GITHUB_ENV
          echo "$GITHUB_ENV" >&2
          echo "$(cat raw.out)" >&2
          echo "$(cat txn.out)" >&2
      - name: Run Integration Test
        run: mvn clean test
